Caso 2
Elissdev/Testes-do-Firefly pull request #4
Opened 2024-06-26 00:47 UTC by Elissdev

2024-06-26 01:03 UTC, Elissdev commented
![Screen Capture_select-area_20240625215533](https://github.com/Elissdev/Testes-do-Firefly/assets/141097995/36abb127-34e6-470e-96f8-ed9ba527804f)

2024-06-26 01:04 UTC, Elissdev commented
![Screen Capture_select-area_20240625215533](https://github.com/Elissdev/Testes-do-Firefly/assets/141097995/280a0b7b-9de9-40c8-8629-015e5b8f2e2c)

2024-07-11 11:05 UTC, nawarian requested changes
Solicitei algumas mudanças pequenas. Aplicar estes princípios a todos os arquivos que tu escrever daqui pra frente neste repositório  :)

2024-07-11 11:05 UTC, nawarian commented on Caso 1 - Login funcional/Caso 1 - Login funcional/autenticacao.validacao.md
> +| Nome  | Valor |
Nome e Valor ficaram como linhas comuns em vez de linhas de título. Assim fica difícil de ler a tabela. Recomendo separar os títulos utilizando o markdown `##` e manter as tabelas somente com as colunas e linhas relevantes. Por exemplo:

```
## Dados de teste

| Nome | Valor | 
| ------- | ------- | 
| Email | demo@firefly |
| Senha | demo | 
```

O resultado ficaria assim:


## Dados de teste

| Nome | Valor | 
| ------- | ------- | 
| Email | demo@firefly |
| Senha | demo |

2024-07-11 11:05 UTC, nawarian commented on Caso 1 - Login funcional/Caso 1 - Login funcional/autenticacao.validacao.md
> +| Nome  | Valor |
Aplicar este princípio em todas as tabelas.

2024-07-11 11:05 UTC, nawarian commented on Caso 2 - Falha de Login/autentificação-falha.md
> +| Requisito    | Quando a senha ou o usuario der incorreto, exibir uma mensagem de erro |
[...] exibir uma mensagem de erro **e não autenticar**

2024-07-11 11:05 UTC, nawarian commented on Caso 2 - Falha de Login/autentificação-falha.md
> +| 1 | These credentials do not match our records |
Não está claro para mim o que é esta pós condição.

2024-07-11 11:05 UTC, nawarian commented on Caso 2 - Falha de Login/autentificação-falha.md
> +| 1 | Visite o endereço: [Firefly III](https://demo.firefly-iii.org/login) | Será direcionado para pagina de login | Sucesso |
Remover coluna "sucesso"

2024-08-04 13:41 UTC, nawarian approved these changes

2024-08-04 13:42 UTC, merged